version: 2

sources:
  - name: bronze
    database: food_delivery
    schema: "{{ 'gold_dbt_ci' if target.name == 'ci' else 'bronze' }}"
    tables:
      - name: dim_customers
      - name: dim_vendors
      - name: dim_drivers
      - name: dim_menu_items
    
  - name: silver
    database: food_delivery
    schema: "{{ 'gold_dbt_ci' if target.name == 'ci' else 'silver' }}"
    tables:
      - name: order_events
        columns:
          - name: event_id
            tests:
              - unique
              - not_null